@hostname = http://localhost:5182/api

GET {{hostname}}/jarmuvek/
Accept: application/json

###

GET {{hostname}}/jarmuvek?page=1&itemsPerPage=20&searchKey=Lada&sortKey=szerviz_datum&ascending=false
Accept: application/json

###

